apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-o4hx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-o4hx@sha256:9e262557be2f4f914a388b985c8d1faf3740ef32914f3b767d6f3cd41e17f353
        name: my-nodejs
        resources: {}
status: {}
